---
# Include Installation tasks for specific OS
    - name: Include Tasks for CentOS or RedHat
      include_tasks: setup-redhat.yml
      when: 
        - ansible_os_family == "RedHat"
        - ansible_distribution != "Fedora"

    - name: Include tasks for Debian
      include_tasks: setup-debian.yml
      when:
        - ansible_distribution == "Debian"

    - name: Include tasks for Ubuntu
      include_tasks: setup-ubuntu.yml
      when:
        - ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "16.04"

    - name: Include tasks for Ubuntu <= 16.04
      include_tasks: setup-ubuntu16.04.yml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version <= "16.04"

    - name: Include tasks for Fedora
      include_tasks: setup-fedora.yml
      when: ansible_distribution == "Fedora"

