---
- name: Include Tasks for CentOS and RedHat
  include_tasks: setup-redhat.yaml
  when: 
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

# Installation of OTC-extensions

- name: Install otcextensions and openstacksdk
  pip:
    executable: pip3
    name:
      - otcextensions
      - python-openstackclient
