---
# extensions_state == present
- block:
    # Installation of OS dependencies
    - name: Include Tasks for CentOS and RedHat
      include_tasks: setup-redhat.yml
      when: 
        - ansible_os_family == "RedHat"
        - ansible_distribution != "Fedora"

    - name: Include tasks for Debian and Ubuntu
      include_tasks: setup-debian.yml
      when:
        - ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" and ansible_distribution_major_version > "16.04"

    - name: Include tasks for Ubuntu <= 16.04
      include_tasks: setup-ubuntu16.04.yml
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version <= "16.04"

  when: extensions_state == "present"

