---
- name: Install package dependencies
  become: yes
  apt:
    name:
      - gcc
      - python3
      - python3-dev
      - python3-pip
      - libssl-dev
    state: "{{ extensions_state }}"
    update_cache: yes

- name: Install otcextensions and openstacksdk for Ubuntu <= 16.04
  pip:
    executable: pip3
    name:
      - otcextensions
      - python-openstackclient
    state: "{{ extensions_state }}"
    extra_args: --user
