---
- name: Install package dependencies for Fedora
  become: yes
  package: 
    state: "{{ extensions_state }}"
    name: "{{ item }}"
  with_items:
    - gcc
    - python3
    - python3-devel
    - python3-pip
    - openssl-devel
  when: extensions_state == "present" 

- name: Install / Remove otcextensions and openstacksdk for Fedora
  become: yes
  pip:
    executable: pip3
    name:
      - otcextensions
      - python-openstackclient
    state: "{{ extensions_state }}"
