---
- name: Install package dependencies for Ubuntu
  become: yes
  apt:
    name:
      - gcc
      - python3
      - python3-dev
      - python3-pip
      - libssl-dev
    state: "{{ extensions_state }}"
    update_cache: yes
  when: extensions_state == "present"

- name: Update pip
  become: yes
  pip:
    executable: pip3
    name:
      - pip
    state: latest
  when: extensions_state == "present"


- name: Install setuptools for Ubuntu <= 16.04
  pip:
    executable: pip3
    name:
      - setuptools
    extra_args: --user
  when: extensions_state == "present"


- name: Install otcextensions and openstacksdk for Ubuntu <= 16.04
  pip:
    executable: pip3
    name:
      - otcextensions
      - python-openstackclient
    state: "{{ extensions_state }}"
    extra_args: --user

