---
- name: Install package dependencies
  become: yes
  apt:
    name:
      - gcc
      - python3
      - python3-dev
      - python3-pip
      - libssl-dev
    state: "{{ extensions_state }}"
    update_cache: yes

- name: Upgrade pip
  become: yes
  command: pip3 install --upgrade pip

